export { CreatePagesService } from './CreatePagesService'
export { DeletePagesService } from './DeletePagesService'
export { GetPagesService } from './GetPagesService'
export { ListPagesService } from './ListPagesService'
export { UpdatePagesService } from './UpdatePagesService'
